[package]
name = "provider_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = { workspace = true }
proc-macro2 = { workspace = true }
syn = { workspace = true, features = ["full"] }
helpers = { path = "../helpers" }

[lib]
proc-macro = true