[package]
name = "integration_tests"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
state_macro = { path = "../state_macro" }
provider_macro = { path = "../provider_macro" }

[[test]]
name = "state"
test = false